folio-org/ui-checkin

- Scan.js
And import `PropTypes` from `prop-types`, not `React`.
> Import PropTypes from prop-types. Refs STRIPES-427

- CheckIn.js
- Scan.js
- package.json
- util.js
> Uichkin 10 refinement

- Scan.js
- util.js
Reverts folio-org/ui-checkin#25
> Revert "Refine the util file in UICHKIN to return a dateTime in UTC to be sen…"

- Scan.js
- package.json
https://issues.folio.org/browse/STCOM-284
Components previously found in `@folio/stripes-components/lib/structures` are now at `@folio/stripes-components/lib`.
> STCOM-284 Update stripes-components paths

- CHANGELOG.md
- CheckIn.js
- Scan.js
- index.js
https://issues.folio.org/browse/UICHKIN-31
> Fix focus issues. Fixes UICHKIN-31.

- CheckIn.js
- Scan.js
- bigtest/interactors/check-in.js
- bigtest/network/factories/item.js
- bigtest/tests/check-in-test.js
- package.json
Bringing over from https://github.com/cherewaty/ui-checkin/pull/1
Thanks @tkrose 👏
> Add tests for navigating the dropdown menu, changing check-in date/time, and submitting without a barcode

- translations/ui-checkin/de.json
- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20180913T150458

- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20181026T143111

- src/components/ConfirmStatusModal/ConfirmStatusModal.js
- translations/ui-checkin/en.json
This PR introduces couple more changes based on the feedback in https://issues.folio.org/browse/UICHKIN-16
> Update confirm status modal. Part of UICHKIN-16

- CHANGELOG.md
- src/CheckIn.js
- translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-14
> Extract hardcoded labels. Part of UICHKIN-14

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20181031T224505

- package.json
- src/Scan.js
Provide `checkinServicePointId` during checkin. 
Refs [UICHKIN-55](https://issues.folio.org/browse/UICHKIN-55)
> provide checkinServicePointId during checkin

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20181128T202334

- CHANGELOG.md
- src/CheckIn.js
- src/Scan.js
This PR should handle checking in the items in transit but also items without loan. 
https://issues.folio.org/browse/UICHKIN-44
> Handle check in for items that are In transit. Part UICHKIN-44.

- CHANGELOG.md
- src/CheckIn.js
https://issues.folio.org/browse/UICHKIN-40
> Display destination service point for in transit items. Fixes UICHKIN-40

- CHANGELOG.md
- src/CheckIn.js
https://issues.folio.org/browse/UICHKIN-61
> Fix link to item. Fixes UICHKIN-61

- CHANGELOG.md
- src/CheckIn.js
- src/Scan.js
- translations/ui-checkin/en_US.json
We are adding:
* Add New fee/fine option on ellipsis menu. Refs [UICHKIN-56](https://issues.folio.org/browse/UICHKIN-56).
> Add New fee/fine option

- src/Scan.js
- src/components/ConfirmStatusModal/ConfirmStatusModal.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/interactors/check-in.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/service-point.js
- test/bigtest/network/factories/staff-slip.js
- test/bigtest/network/models/service-point.js
- test/bigtest/network/models/staff-slip.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/network/serializers/okapi.js
- test/bigtest/network/serializers/service-point.js
- test/bigtest/network/serializers/staff-slip.js
- test/bigtest/tests/check-in-test.js
https://issues.folio.org/browse/UICHKIN-53
> Inherit check-in modal print slip print defaults from service point. Part of UICHKIN-53.

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICHKIN-83
> Update circulation OKAPI interface to v7.0. Part of UICHKIN-83.

- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/pt_PT.json
> Update translation strings as of 20190222T002228

- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20190227T140407

- translations/ui-checkin/en_US.json
> Update translation strings as of 20190228T144944

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20190321T130117

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20190405T144349

- src/ModalManager.js
- src/Scan.js
- src/components/CheckinNoteModal/CheckinNoteModal.js
- src/consts.js
- src/util.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
This PR fixes issues with the pre checkin modals described in https://issues.folio.org/browse/UICHKIN-79
The modals should appear one after another. The last shown modal should trigger checkin process after confirmation.
> Refactor modals during check in. Part of UICHKIN-79.

- src/CheckIn.js
- src/Scan.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
Cancel multipiece check in clears check in history.
> UICHKIN-88: Delete resources clear on modal close.

- translations/ui-checkin/es_ES.json
> Update translation strings as of 20190425T181703

- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20190501T184815

- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20190520T224011

- src/ModalManager.js
- src/components/CheckinNoteModal/CheckinNoteModal.js
- src/components/ComponentToPrint/ComponentToPrint.js
- src/util.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
- translations/ui-checkin/en.json
Display date and source for check in notes.
> UICHKIN-87: Add column with date and source.

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20190718T013203

- src/CheckIn.js
- src/Scan.js
- src/util.js
- test/bigtest/tests/check-in-test.js
Update print slip functionality in order to support new tokens.
https://issues.folio.org/browse/UICIRC-189
Fill template with data from staffSlipsContext field for check-in response.
> UICIRC-189 - Refine list of tokens available for staff slip templates

- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20190718T220243

- src/util.js
To deny formate date if its value equal to null.
> fix/dispaly-staff-slips-dates - Deny formatting null values

- src/util.js
To add new tokens for staff slips
https://issues.folio.org/browse/UICIRC-300
> UICIRC-300 - Add copy, loanType and numberOfPieces tokens to staff slips

- src/ModalManager.css
- src/ModalManager.js
Update checkin notes modals
https://issues.folio.org/browse/UICHKIN-106
> UICHKIN-106 - changed fields order, fixed styles.

- translations/ui-checkin/it_IT.json
> Update translation strings as of 20190823T080157

- src/util.js
Add "lastCheckedInDateTime" and remove "lastScannedServicePoint" tokens for staff slips
https://issues.folio.org/browse/UICIRC-291
> UICIRC-291 - Add "lastCheckedInDateTime" and remove "lastScannedServicePoint" tokens for staff slips

- translations/ui-checkin/ar.json
> Update translation strings as of 20191004T135530

- src/util.js
To fix page failure if BE sends null value for source object
https://issues.folio.org/browse/UICHKIN-107
Replace js destructuring with lodash get method
> UICHKIN-107 - System error occurs when checking in a specific book

- CHANGELOG.md
- src/CheckIn.js
- src/Scan.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
Display the time of scan for checked-in items, even if the items weren't checked out. [Story](https://issues.folio.org/browse/UICHKIN-63).
**Demo**
> UICHKIN-63: Show time of scan when checking any item in

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20191106T134035

- translations/ui-checkin/it_IT.json
> Update translation strings as of 20191119T231120

- CHANGELOG.md
- package.json
- src/CheckIn.js
- src/Scan.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
Show that check-in is processing in the scope of [UICHKIN-129](https://issues.folio.org/browse/UICHKIN-129).
> UICHKIN-129: Implement loader while checkin is processing

- translations/ui-checkin/es_ES.json
> Update translation strings as of 20191220T155503

- src/CheckIn.js
- translations/ui-checkin/en.json
Provide the proper translation for the effective call number
> UICHKIN-127: Provide the proper translation for the effective call number

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200110T211826

- CHANGELOG.md
- src/CheckIn.js
- test/bigtest/interactors/check-in.js
- translations/ui-checkin/en.json
Add tooltip and replace dropdown in order to make in accessable. 
https://issues.folio.org/browse/UICHKIN-134
> UICHKIN-134 - Make the Check in ellipsis accessible

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200117T173544

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICHKIN-149
> UICHKIN-149: Update okapi interfaces

- CHANGELOG.md
- src/CheckIn.js
- src/Scan.js
- translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-100
Note that this is using a placeholder icon for now, as a proper icon has not yet been created.
> UICHKIN-100: Add 'in-house use' column to item table

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200127T144839

- CHANGELOG.md
- src/ModalManager.js
- src/consts.js
- test/bigtest/interactors/check-in.js
- test/bigtest/interactors/declared-lost-modal.js
- test/bigtest/tests/check-in-test.js
- translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-114
> UICHKIN-114: Add declared lost modal

- CHANGELOG.md
- package.json
- src/CheckIn.js
- test/bigtest/tests/check-in-test.js
Display 
- effective call number prefix, 
- call number ,
- call number, 
- suffix,
- enumeration,
- chronology,
- volume
in loans contexts
https://issues.folio.org/browse/UIU-1347
https://issues.folio.org/browse/UIU-1391
> UIU-1391: display Effective call number string info

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/ur.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200220T141728

- CHANGELOG.md
- src/CheckIn.js
Fix several accessibility problems
https://issues.folio.org/browse/UICHKIN-159
> Fix several accessibility problems

- CHANGELOG.md
- src/CheckIn.js
Fix accessibility problems
https://issues.folio.org/browse/UICHKIN-159
> UICHKIN-159: fix accessibility problems

- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20200302T163727

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/ur.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200309T000645

- translations/ui-checkin/ru.json
> Update translation strings as of 20200312T133304

- translations/ui-checkin/fr_FR.json
> Update translation strings as of 20200316T134017

- translations/ui-checkin/ru.json
> Update translation strings as of 20200317T123814

- translations/ui-checkin/ja.json
> Update translation strings as of 20200331T152557

- src/Scan.js
Fix sending duplicate emails for patron with several loans.
https://issues.folio.org/browse/UICHKIN-176
*Before*
*After*
> UICHKIN-176 - Three identical e-mail notices for one check in session

- translations/ui-checkin/ja.json
> Update translation strings as of 20200415T223222

- src/Scan.js
* Update unique patron selection algorithm.
* Fix sending duplicate emails for patron with several loans.
Refs [UICHKIN-176](https://issues.folio.org/browse/UICHKIN-176)
> UICHKIN-176 do not send duplicate check-in notices

- CHANGELOG.md
- src/CheckIn.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
- translations/ui-checkin/en.json
If checking in an item with at least one open request then add link to request details in action menu
https://issues.folio.org/browse/UICHKIN-103
> UICHKIN-103: Add link to request details in action menu

- translations/ui-checkin/ru.json
> Update translation strings as of 20200515T182823

- src/CheckIn.js
While working on another ticket I noticed that the ellipsis button was a bit buggy and that the implementation of the ellipsis button and tooltip could be improved a bit.
- Changed the `<Button>` to a `<IconButton>`
- Moved the button inside the `<Tooltip>`
> Updated check-in ellipsis button/tooltip implementation.

- src/CheckIn.js
- test/bigtest/interactors/check-in.js
- test/bigtest/network/factories/request.js
- test/bigtest/network/scenarios/check-in-by-barcode-with-request.js
- test/bigtest/tests/check-in-requested-item-test.js
- test/bigtest/tests/check-in-test.js
Fix. Add link if checking in an item with at least one open request then add link to request details in action menu
https://issues.folio.org/browse/UICHKIN-103
> UICHKIN-103: Add link to request details page

- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20200526T141248

- translations/ui-checkin/fr_FR.json
> Update translation strings as of 20200602T151309

- src/components/FeesFinesOwnedStatus/FeesFinesOwnedStatus.js
- translations/ui-checkin/en.json
Change check-in message from `fee/fine owned` to `fee/fine owed` 
https://issues.folio.org/browse/UICHKIN-179
> UICHKIN-179: Fix translation

- translations/ui-checkin/ru.json
> Update translation strings as of 20200701T150841

- translations/ui-checkin/pt_BR.json
> Update translation strings as of 20200707T213422

- translations/ui-checkin/fr_FR.json
> Update translation strings as of 20200716T140311

- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20200721T202356

- translations/ui-checkin/it_IT.json
> Update translation strings as of 20200723T031126

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/ur.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200820T141724

- translations/ui-checkin/it_IT.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/zh_CN.json
> Update translation strings as of 20200824T140725

- translations/ui-checkin/it_IT.json
> Update translation strings as of 20200827T215834

- CHANGELOG.md
- package.json
- src/CheckIn.js
- src/index.js
- Update `react-intl` to `v5.7.0`
- Fix console errors
- Remove invalid prop
> Update react-intl to v5.7.0

- CHANGELOG.md
- translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-201
> UICHKIN-201: Localize permission names

- translations/ui-checkin/ar.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/de.json
- translations/ui-checkin/en_GB.json
- translations/ui-checkin/en_SE.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/fr_FR.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hi_IN.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/it_IT.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/ko.json
- translations/ui-checkin/pl.json
- translations/ui-checkin/pt_BR.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ru.json
- translations/ui-checkin/ur.json
- translations/ui-checkin/zh_CN.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20200928T202231

- CHANGELOG.md
- src/ModalManager.js
- src/util.js
Use `getFullName` from stripes-util to correctly show last and first name.
https://issues.folio.org/browse/UICHKIN-147
> UICHKIN-147:  Display source as last name, first name

- translations/ui-checkin/de.json
> Update translation strings as of 20201005T202004

- translations/ui-checkin/de.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
> Update translation strings as of 20201016T144229

- translations/ui-checkin/ja.json
> Update translation strings as of 20201102T140138

- CHANGELOG.md
- package.json
- src/CheckIn.js
- src/Scan.js
- src/util.js
Value in `Timepicker` is the local tenant's timezone time - "now" 
https://issues.folio.org/browse/UICHKIN-206
> UICHKIN-206: Set TimePicker to tenant's time

- translations/ui-checkin/it_IT.json
> Update translation strings as of 20201119T214636

- src/CheckIn.js
- src/util.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/check-in-test.js
https://issues.folio.org/browse/UICHKIN-214
- Added autoFocus for the barcode input to move focus on mount
- Added click event listener on the current app button that moves focus to the barcode input on click
> UICHKIN-214: Update focus management

- CHANGELOG.md
- translations/ui-checkin/en.json
- translations/ui-checkin/en_US.json
https://issues.folio.org/browse/UICHKIN-211
> UICHKIN-211: Fix typo in status label

- translations/ui-checkin/ber.json
- translations/ui-checkin/ca.json
- translations/ui-checkin/da.json
- translations/ui-checkin/en_US.json
- translations/ui-checkin/es.json
- translations/ui-checkin/es_419.json
- translations/ui-checkin/es_ES.json
- translations/ui-checkin/fr.json
- translations/ui-checkin/he.json
- translations/ui-checkin/hi_IN.json
- translations/ui-checkin/hu.json
- translations/ui-checkin/ja.json
- translations/ui-checkin/ko.json
- translations/ui-checkin/pl.json
- translations/ui-checkin/pt_PT.json
- translations/ui-checkin/ur.json
- translations/ui-checkin/zh_TW.json
> Update translation strings as of 20201124T212804

- CHANGELOG.md
- src/ModalManager.js
- src/consts.js
- test/bigtest/tests/check-in-test.js
- translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-221
> UICHKIN-221 - Check in items with Restricted status

- CHANGELOG.md
- package.json
Update module to stripes v6.
https://issues.folio.org/browse/UICHKIN-226
> UICHKIN-226 - update to stripes v6.

- .gitignore
- CHANGELOG.md
- src/CheckIn.js
- src/Scan.js
Fix incorrect ref assignment
https://issues.folio.org/browse/UICHKIN-205
> UICHKIN-205: fix incorrect ref assignment

- CHANGELOG.md
- package.json
- Increment @folio/stripes-cli to v2
https://issues.folio.org/browse/UICHKIN-231
> UICHKIN-231: Increment @folio/stripes-cli to v2

- .gitignore
- CHANGELOG.md
https://issues.folio.org/browse/UICHKIN-232
> UICHKIN-232: Update .gitignore file

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- Add pull request template
https://issues.folio.org/browse/UICHKIN-233
> UICHKIN-233: Add pull request template

- CHANGELOG.md
- src/CheckIn.js
Added checking if element exists before `event listeners` will be added. If we go between pages there is the case when element `#ModuleMainHeading` has not mounted yet. So we should take care about this case and add event listener after element will render. So I added the checking in `componentDidUpdate` life cycle as well, and the flag to state `hasEventListener` for reduce amount of code execution. 
https://issues.folio.org/browse/UICHKIN-239
- Do JIRAs exist to update the …
> UICHKIN-239: Navigating back to Checkin page leads to error message

- CHANGELOG.md
- src/util.js
Add patron comment token for staff slips
https://issues.folio.org/browse/UICHKIN-248
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While …
> UICHKIN-248: Add patron comment token for staff slips

- CHANGELOG.md
We should add changes to CHANGELOG file about bug fix release v5.0.2 after bug fix release v5.0.2
https://issues.folio.org/browse/UICHKIN-246
> UICHKIN-246: Update CHANGELOG after bug fix v5.0.2

- CHANGELOG.md
We should add changes to CHANGELOG file about bug fix release v5.0.3 after bug fix release v5.0.3
https://issues.folio.org/browse/UICHKIN-249
> UICHKIN-249: Update CHANGELOG after bug fix v5.0.3

- test/jest/babel.config.js
* consistently configure plugins. See also folio-org/stripes-webpack/pull/18
* support new JSX transform. See also folio-org/stripes-webpack/pull/11
> update test babel config to avoid errors

- src/Scan.js
Validate the `loanItem` attribute before accessing its attributes.
Refs [UICHKIN-274](https://issues.folio.org/browse/UICHKIN-274)
> UICHKIN-274 validate attributes before accessing them

- CHANGELOG.md
- src/util.js
- src/util.test.js
Undefined Bar Code - Requester info not showing
https://issues.folio.org/browse/UICHKIN-276
**Before**
**After**
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UICHKIN-276: Remove undefined barcode

- Jenkinsfile
> FOLIO-3224 verify changes in jenkins-pipeline-libs

- CHANGELOG.md
- package.json
You will not be able to commit the above changes until Monday, September 13, 2021 when these changes are committed in the stripes-* repos. 
Increment `stripes` to `v7`, `react` to `v17`
https://issues.folio.org/browse/UICHKIN-290
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> UICHKIN-290: Update stripes version

- CHANGELOG.md
Update changelog after bug fix v6.0.1
https://issues.folio.org/browse/UICHKIN-315
> Update changelog after bug fix v6.0.1

- CHANGELOG.md
- package.json
Remove webpack from dependencies
https://issues.folio.org/browse/UICHKIN-316
> UICHKIN-316: remove webpack from dependencies

- CHANGELOG.md
- src/components/CheckInFooter/CheckInFooter.js
- src/components/CheckInFooter/CheckInFooter.test.js
- test/jest/__mock__/stripesComponents.mock.js
UICHKIN-278: Add RTL/Jest testing for `CheckInFooter` component
* Add RTL/Jest testing for `CheckInFooter` component
* Removed unnecessary layout parts without visible changes.
https://issues.folio.org/browse/UICHKIN-278
> UICHKIN-278: Add RTL/Jest testing for `CheckInFooter` component

- CHANGELOG.md
- package.json
- test/bigtest/tests/check-in-with-claimed-returned-test.js
Update mocha in package.json
This PR solve the problem of tests run.
https://issues.folio.org/browse/UICHKIN-324
> UICHKIN-324: Update mocha

- CHANGELOG.md
- package.json
Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UICHKIN-310
> UICHKIN-310: support `circulation` `12.0`

- CHANGELOG.md
- src/CheckIn.js
- src/components/SelectItemModal/SelectItemModal.js
Add id for Pane component.
https://issues.folio.org/browse/UICHKIN-329
> UICHKIN-329: Add id for Pane component.

- CHANGELOG.md
- src/components/CheckinNoteModal/CheckInNoteModal.test.js
- test/jest/__mock__/stripesComponents.mock.js
[UICHKIN-279](https://issues.folio.org/browse/UICHKIN-279)
Cover CheckinNoteModal component by RTL/Jest tests
[https://issues.folio.org/browse/UICHKIN-279](https://issues.folio.org/browse/UICHKIN-279)
Code coverage of CheckinNoteModal component is 100%
> UICHKIN-279 Add tests to CheckinNoteModal component

- CHANGELOG.md
- package.json
Update changelog after module release.
https://issues.folio.org/browse/UICHKIN-335
> UICHKIN-335: changelog update after release

- CHANGELOG.md
- src/components/PrintButton/PrintButton.test.js
Cover `PrintButton` component by RTL/jest tests.
[UICHKIN-285](https://issues.folio.org/browse/UICHKIN-285)
> Cover `PrintButton` component by RTL/jest tests.

- CHANGELOG.md
- package.json
- src/index.js
Remove react-hot-loader
https://issues.folio.org/browse/UICHKIN-333
> UICHKIN-333: Remove react-hot-loader

- CHANGELOG.md
- karma.conf.js
- test/bigtest/constants.js
- test/bigtest/interactors/check-in.js
- test/bigtest/tests/automated-end-session-test.js
- test/bigtest/tests/check-in-requested-item-test.js
- test/bigtest/tests/check-in-test.js
- test/bigtest/tests/check-in-with-claimed-returned-test.js
- test/bigtest/tests/claimed-returned-modal-test.js
- test/bigtest/tests/fee-fine-test.js
Improvement for bigtest running
* After fix skipped tests was returned
* 1 test was removed because before sending data we use function for convert data "buildDateTime" this function depends on time zone. Send and input data(date and time) can be different after convert with using time zone
https://issues.folio.org/browse/UICHKIN-341
> UICHKIN-341: Improvement for bigtest running

- CHANGELOG.md
- src/components/ComponentToPrint/ComponentToPrint.js
- src/components/ComponentToPrint/ComponentToPrint.test.js
Add Jest/RTL testing for `ComponentToPrint` component.
https://issues.folio.org/browse/UICHKIN-281
> UICHKIN-281: add Jest/RTL tests for `ComponentToPrint` component.

- CHANGELOG.md
[UICHKIN-346](https://issues.folio.org/browse/UICHKIN-346)
> UICHKIN-346: Update changelog after release

- CHANGELOG.md
- src/components/MultipieceModal/MultipieceModal.js
- src/components/MultipieceModal/MultipieceModal.test.js
Remove hardcoded empty values
https://issues.folio.org/browse/UICHKIN-356
> UICHKIN-356: Remove hardcoded empty values

- CHANGELOG.md
- src/Scan.js
- src/consts.js
- test/bigtest/tests/check-in-with-claimed-returned-actual-cost-test.js
UICHKIN-372: Claimed returned: cancel ACTUAL COST fee at check in
https://issues.folio.org/browse/UICHKIN-372
Hello @iselagb thank you for your pull request. Due to problems with the build, I copied your changes to this pull.
This pull request was copied from https://github.com/folio-org/ui-checkin/pull/565
> UICHKIN-372: Claimed returned: cancel ACTUAL COST fee at check in

- CHANGELOG.md
- src/index.js
- src/index.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/__mock__/stripesFinalForm.mock.js
UI tests replacement with RTL/Jest for index.js
https://issues.folio.org/browse/UICHKIN-362
> UICHKIN-362: UI tests replacement with RTL/Jest for index.js

- CHANGELOG.md
- package.json
R1 2023 Orchid module release 8.0.0
[UICHKIN-374](https://issues.folio.org/browse/UICHKIN-374)
> UICHKIN-374: R1 2023 Orchid module release 8.0.0

- CHANGELOG.md
- src/CheckIn.js
- src/components/CheckinDateTime/CheckinDateTime.js
- src/components/CheckinDateTime/CheckinDateTime.test.js
- src/util.js
- src/util.test.js
Fix incorrect checkin time
https://issues.folio.org/browse/UICHKIN-377
> UICHKIN-377: Fix incorrect checkin time

- CHANGELOG.md
Update changelog after release
https://issues.folio.org/browse/UICHKIN-380
> UICHKIN-380: Update changelog after release

- CHANGELOG.md
- src/util.js
- src/util.test.js
Populate the token "requester.departments" in the hold, request delivery and transit slips, with the data provided by the backend in the ui-checkin module
Add a new token "departments" to requester group on staff slips
https://issues.folio.org/browse/UICHKIN-350
**Item and Request information**
**User**
Staff **slip**
Ideally all of the PRs involved in …
> UICHKIN-350 - add requester.departments to slip data

- src/util.js
- src/util.test.js
- test/jest/fixtures/loan.js
Update staff slips to have the primary service point for an effective location
Added a new token for primary service point.
https://issues.folio.org/browse/CIRC-1785
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> CIRC-1785 added new token effectiveLocationPrimaryServicePointName

- CHANGELOG.md
- package.json
Also support circulation 14.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UICHKIN-381
> UICHKIN-381: Also support circulation 14.0

- CHANGELOG.md
- src/util.js
- src/util.test.js
Update staff slips to have the request date
add new token for request date
https://issues.folio.org/browse/UICHKIN-384
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UICHKIN-384 added request.requestDate token

- src/Scan.js
Add sessionId field to check-in request body JSON
https://issues.folio.org/browse/UICHKIN-385
##Approach
We migrate approach of saving data from state that was implemented in https://github.com/folio-org/ui-checkin/pull/589 to resources for correct saving data.
Test will be implemented in scope of https://issues.folio.org/browse/UICHKIN-289
CHANGELOG.md was updated in https://github.com/folio-org/ui-checkin/pull/589
> UICHKIN-385: Add sessionId field to check-in request body JSON

- CHANGELOG.md
- package.json
- src/components/CheckInFooter/CheckInFooter.test.js
Add possible for run axe tests
https://issues.folio.org/browse/UICHKIN-386
> UICHKIN-386: Add possible for run axe tests

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node.js to v18 in GitHub Actions
https://issues.folio.org/browse/UICHKIN-390
> UICHKIN-390: Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- src/components/FeeFineDetailsButton/FeeFineDetailsButton.test.js
- src/index.js
- src/index.test.js
Fix issues with skipped tests
[UICHKIN-395](https://issues.folio.org/browse/UICHKIN-395)
> UICHKIN-395: Fix issues with skipped tests

- CHANGELOG.md
- src/ModalManager.test.js
- src/components/CheckInFooter/CheckInFooter.test.js
- src/components/CheckedInListItems/CheckedInListItems.test.js
- src/components/CheckedInListItems/components/FeesFinesOwnedStatus/FeesFinesOwnedStatus.test.js
- src/components/CheckedInListItems/components/ReturnedTime/ReturnedTime.test.js
- src/components/CheckinDateTime/CheckinDateTime.test.js
- src/components/CheckinNoteModal/CheckInNoteModal.test.js
- src/components/ClaimedReturnedModal/ClaimedReturnedModal.test.js
- src/components/ComponentToPrint/ComponentToPrint.test.js
- src/components/ConfirmStatusModal/ConfirmStatusModal.test.js
- src/components/FeeFineDetailsButton/FeeFineDetailsButton.test.js
- src/components/MultipieceModal/MultipieceModal.test.js
- src/components/PrintButton/PrintButton.test.js
- src/components/RouteForDeliveryModal/RouteForDeliveryModal.test.js
- src/components/SelectItemModal/SelectItemModal.test.js
Remove outdated imports
https://issues.folio.org/browse/UICHKIN-397
> UICHKIN-397: Remove outdated imports

- CHANGELOG.md
- test/jest/helpers/utils.js
Fix import for utils.js
https://issues.folio.org/browse/UICHKIN-405
> UICHKIN-405: Fix import for utils.js

- CHANGELOG.md
- src/CheckIn.js
- src/components/FeeFineDetailsButton/FeeFineDetailsButton.js
- src/components/FeeFineDetailsButton/FeeFineDetailsButton.test.js
- src/consts.js
- src/util.js
- src/util.test.js
[DCB] Check-in: Hide Fee/Fine action menu options (Lending library)
[UICHKIN-398](https://issues.folio.org/browse/UICHKIN-398)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UICHKIN-398 - Hide 'new fee/fine' menu item for dcb user

- src/Scan.js
- src/Scan.test.js
- src/consts.js
Increase code coverage of Scan component
[UICHKIN-412](https://issues.folio.org/browse/UICHKIN-412)
> UICHKIN-412: UI tests replacement with RTL/Jest for view Scan (part 2)

- CHANGELOG.md
- src/util.js
- src/util.test.js
Add support for displaySummary token for Staff Slips
https://issues.folio.org/browse/UICHKIN-415
> UICHKIN-415: Add support for displaySummary token for Staff Slips

- CHANGELOG.md
Update changelog after release
[UICHKIN-419](https://folio-org.atlassian.net/browse/UICHKIN-419)
> UICHKIN-419: Update changelog after release

- CHANGELOG.md
- package.json
Update changelog and package.json
[UICHKIN-419](https://folio-org.atlassian.net/browse/UICHKIN-419)
> UICHKIN-419: Update changelog and package.json

- CHANGELOG.md
Update CHANGELOG.md after release
https://issues.folio.org/browse/UICHKIN-423
> UICHKIN-423: Update CHANGELOG.md after release

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
Remove bigtests from github actions
https://issues.folio.org/browse/UICHKIN-425
> UICHKIN-425: Remove bigtests from github actions

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
Update upload-artifact actions from v1 and v2 to v4
https://issues.folio.org/browse/UICHKIN-431
> UICHKIN-431: Update upload-artifact actions from v1 and v2 to v4

- CHANGELOG.md
- package.json
- src/components/ComponentToPrint/ComponentToPrint.js
Fix DOMPurify import
https://issues.folio.org/browse/UICHKIN-435
> UICHKIN-435: Fix DOMPurify import

- CHANGELOG.md
- package.json
- src/Scan.js
Migrate from circulation/check-in-by-barcode to circulation-bff/loans/check-in-by-barcode
https://issues.folio.org/browse/UICHKIN-437
> Migrate from circulation/check-in-by-barcode to circulation-bff/loans/check-in-by-barcode. Refs UICHKIN-437

- CHANGELOG.md
- src/components/CheckedInListItems/CheckedInListItems.js
- src/components/CheckedInListItems/CheckedInListItems.test.js
- src/components/SelectItemModal/SelectItemModal.js
- src/components/SelectItemModal/SelectItemModal.test.js
- test/jest/__mock__/stripesComponents.mock.js
Implement support for fields without information
https://folio-org.atlassian.net/browse/UICHKIN-454
> UICHKIN-454: Implement support for fields without information

- CHANGELOG.md
- src/CheckIn.js
Avoid occasional null-pointer exception
https://folio-org.atlassian.net/browse/UICHKIN-486
> [UICHKIN-486] Avoid occasional null-pointer exception

- src/CheckIn.js
- src/components/CheckedInListItems/CheckedInListItems.js
* PropTypes.arrayOf expects a type, not an object
* Use correct PropTypes for ref
> UICHKIN-494 proptypes
