folio-org/ui-checkin

CHANGELOG.md, CheckIn.js, package.json
Old versions of react-bootstrap barf up the Warning: Accessing PropTypes via the main React package is deprecated... message. We could just upgrade, but are working to deprecate react-bootstrap anyway.
=> don't use react-bootstrap's Row, Col. Refs STRIPES-427

CHANGELOG.md, package.json
Following the change in name of the metadata property (from metaData to metadata) the circulation interface version needs updating (from 2.2 to 3.0)
=> Update circulation interface dependency UICHKIN-19

Scan.js
- Added `href` props so that `<Button>` would render as a `<a>`. This lets the right-click context menu show regular link-y things like "Open in new tab".
- Cleaned up the navigation methods while I was at it.
=> UICHKIN-27: Converted items' ellipsis menu entries to <a> tags

Scan.js, index.js
https://issues.folio.org/browse/STCOR-208
`context.history` is unused
=> STCOR-208 remove unused context.history

karma.conf.js
Jenkins was reporting `None of the test reports contained any result`, since there was no JUnit-style report being generated.
=> Change test results XML path

test/bigtest/interactors/check-in.js
Until we figure out how to properly export interactors from `stripes-components`.
=> Use own Datepicker and Timepicker interactors

src/Scan.js
It looks like the query responsible for retrieving open requests had to be adjusted and include items with status = `Open - Awaiting pickup`.
=> Update requests query. Part of UICHKIN-16

src/CheckIn.js, src/Scan.js
It looks like because of the multiple hoc wrappers around `CheckIn` 
https://github.com/folio-org/ui-checkin/blob/master/src/CheckIn.js#L245-L247
we are not able to reference the `focusInput` function directly via `this.checkInRef.current.wrappedInstance`. This PR introduces couple small changes to make it easier for accessing `CheckIn` instance directly.
=> Refactor barcode focus. Part of UITEST-55

src/CheckIn.js
Checkin had to resort to pushing a ref through the HOC's that wrap TextField in order to properly obtain a ref so that it could call instance methods of TextField (`focusInput()`)
This isn't an ideal way for things to be shaped.
TextField has a prop: `inputRef` that can be used to obtain a direct ref to the `<input>` rendered by TextField. This will punch through any HOC's without needing to rely on ref-forwarding or `withRef` API. Any usage of `focusInput()` or `getInput()` can be replaced by the native `focus()`. In this case, the API to dig up the rendered component (`getRenderedComponent()`) can be removed as well.
=> STCOM-394 User TextField InputRef prop.

src/components/MultipieceModal/MultipieceModal.js, test/bigtest/interactors/check-in.js, test/bigtest/tests/check-in-test.js
@magdazacharska I'm hoping this PR will bring `ui-checkin` to > 80%.
More tests were added as part of another PR https://github.com/folio-org/ui-checkin/pull/138
Sonarcloud shows me 81.9% coverage after this PR is merged:
https://sonarcloud.io/component_measures?branch=UICHKIN-69&id=org.folio%3Aui-checkin&metric=coverage
I think we can improve this further but let's try to merge this one in and see where we are.
=> Improve ui-checkin BigTest code coverage to >80%. Part of UICHKIN-69.

CHANGELOG.md, src/components/PrintButton/PrintButton.js, src/components/PrintButton/quillEditor.css
Setup quill editor styles so the slip templates render correctly.
https://issues.folio.org/browse/UICHKIN-75
=> Add styles for quill editor. Part of UICHKIN-75.

CHANGELOG.md, src/Scan.js
Submitting an item barcode with leading or trailing whitespace to the
endpoint `circulation/check-in-by-barcode` causes it to fail with a 500
and the response, "Failed to contact storage module:
java.io.IOException: Connection reset by peer".
Fixes [UICHKIN-93](https://issues.folio.org/browse/UICHKIN-93)
=> trim whitespace padding from item barcodes

CHANGELOG.md, package.json, src/components/PrintButton/PrintButton.js
`react-to-print` v1 depends directly on React with a caret dep on
version 16. This has the effect of pulling in the most-recent React 16.x
build into any bundle that uses this module, even if that module has a
more strict tilde dep on a less-than-current React minor release.
Whatnow? Say an app depends on React ~16.8.0; React 16.9.0 still gets
into the bundle because of the loose (caret) direct dependency in
react-to-print v1. This was fixed in
https://github.com/gregnb/react-to-print/pull/53 and appears to be the
straw that broke the v1.0-camel's back.
v2 also changed from using a `window` to an `iframe` to handle printing,
but does not automatically clean up the iframe after printing is
finished. This appears to be an oversight, but rather than introduce
another breaking change, they …
=> UIIN-678 avoid buggy react-to-print version

CHANGELOG.md, package.json
Handle errors with missed backend sub-permissions when a user has only **Check in: All permissions** as a part of [UICHKIN-110](https://issues.folio.org/browse/UICHKIN-110).
=> UICHKIN-110: Provide correct backend permissions in 'Check in: All permissions" permission

src/Scan.js
My last PR broke things a little bit. I changed the code to fetch all requests of an item, including closed requests which don't have a position field. So if an array of closed requests is returned from the back-end, then the `if (requests.length)` condition is truthy, but the code which runs on this condition fails: `const nextRequest = minBy(requests, 'position');`
* fetch requests only with statuses "Open - Awaiting pickup" or "Open - Awaiting delivery"
* The line `const nextRequest = minBy(requests, 'position');`  was changed to `const nextRequest = requests[0];`  since if a request's status is  "Open - Awaiting pickup" or "Open - Awaiting delivery", than it's position is `1`.
=> UICHKIN-138: fix bug on checking in item with no active requests

CHANGELOG.md, package.json
A list of countries is provided in newer versions of stripes-components,
so we need to update the `@folio/stripes` dependency to get that newer
version in order to use those values.
Refs [UICHKIN-146](https://issues.folio.org/browse/UICHKIN-146)
=> UICHKIN-146 update stripes to receive countries

.eslintrc, CHANGELOG.md, package.json, src/CheckIn.js, test/bigtest/interactors/check-in.js, test/bigtest/tests/check-in-test.js
Display effective call number prefix, call number, and call number suffix during check in in the scope of [UICHKIN-127](https://issues.folio.org/browse/UICHKIN-127).
=> UICHKIN-127: Display effective call number prefix, call number, and call number suffix at check in

CHANGELOG.md, package.json
Why a new major version?
* bump the `@folio/stripes` peer to `v3.0.0`
* move `react-router` related things to peerDependencies
* move `react-intl` to peerDependencies
=> bump to version 2.0.0

package.json
Silly yarn isn't clever enough to include peer-deps as dev-deps for the
purposes of testing. C'mon.
=> peer-deps must also be dev deps

CHANGELOG.md, src/CheckIn.js
https://issues.folio.org/browse/UICHKIN-174
This PR wraps fees/fines related components in `< IfPermission>` block to prevent from throwing an error described in UICHKIN-174 when user doesn't have the `accounts.collection.get` permission.
I tried to add tests to this but I unfortunately failed. The BigTest setup in ui-checkin is a bit different from other modules with setup similar to: 
https://github.com/folio-org/ui-checkin/blob/master/.stripesclirc.js
For some reason I could not customize it to add the ability to define what permissions should be used during testing. We will need some more time to review it.
=> UICHKIN-174: Check for accounts.collection.get permission

CHANGELOG.md, src/CheckIn.js
https://issues.folio.org/browse/UICHKIN-175
This PR replaces the path to stripes util from `@folio/stripes-util` to `@folio/stripes/util`
=> UICHKIN-175: Fix import path to stripes util

CHANGELOG.md, src/ModalManager.js, src/consts.js, test/bigtest/interactors/check-in.js, test/bigtest/interactors/withdrawn-modal.js, test/bigtest/tests/check-in-test.js, translations/ui-checkin/en.json
Show confirmation modal when a withdrawn item is checked in
https://issues.folio.org/browse/UICHKIN-126
=> UICHKIN-126: Show confirmation modal when a withdrawn item is checked in

package.json, src/CheckIn.js, src/Scan.js, src/checkin.css, test/bigtest/interactors/check-in.js
Replace redux-form with react final form.
https://issues.folio.org/browse/UICHKIN-157
Main challenges were in migration submit validation errors, because in redux-form we could throw an redux exception form any method, and in final form we should return an object with error from onSubmit callback. One more problem was in change and reset form methods which available only in form component but called from parent component. In order to fix it I've passed additional ref to Checkin component in order to save link to form object.
=> UICHKIN-157 - Refactor forms to use final-form

CHANGELOG.md, src/ModalManager.js, src/Scan.js, src/components/ClaimedReturnedModal/ClaimedReturnedModal.js, src/components/ClaimedReturnedModal/index.js, src/consts.js, test/bigtest/interactors/check-in.js, test/bigtest/interactors/claimed-returned-modal.js, test/bigtest/tests/check-in-test.js, test/bigtest/tests/claimed-returned-modal-test.js, translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-116
This PR adds a modal that handles check-in of items with the status 'Claimed returned'. The return claim has to be resolved by the user in one of two ways, so there are two 'resolution' buttons in the modal that selects an appropriate resolution (which is then saved along with other check-in properties).
=> UICHKIN-116: Add support for Claimed returned items

CHANGELOG.md, src/util.js
If `requester.country` is undefined, don't attempt to retrieve its
translated value because obviously that will fail. `react-intl` throws a
very noisy warning about undefined values and this really pollutes the
test output.
=> don't lookup empty values

.gitignore, src/Scan.js
I modified the checkin submission function to use
the "escapeCqlValue" function to properly escape
characters and added quotation marks to the value.
The error referenced no longer appears, instead
you get a modal telling you the value could not be
found.
Refs: https://issues.folio.org/browse/UICHKIN-185
=> UICHKIN-185: Checkin barcode CQL injection

package.json, test/bigtest/helpers/setup-application.js, test/bigtest/network/factories/item.js, test/bigtest/network/factories/loan.js, test/bigtest/network/factories/request.js, test/bigtest/network/factories/service-point.js, test/bigtest/network/factories/staff-slip.js, test/bigtest/network/factories/user.js, test/bigtest/network/index.js, test/bigtest/network/models/item.js, test/bigtest/network/models/loan.js, test/bigtest/network/models/request.js, test/bigtest/network/models/service-point.js, test/bigtest/network/models/staff-slip.js, test/bigtest/network/models/user.js, test/bigtest/network/serializers/application.js, test/bigtest/network/serializers/okapi.js, test/bigtest/tests/check-in-test.js
`@bigtest/mirage` was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of `miragejs`. This is the first of many refactoring I will be doing in order to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.
- Removed `@bigtest/mirage` and added `inflected`, `faker`, and `miragejs` as dev dependencies.
- Configured `miragejs` as the server type for `setupStripesCore()`.
- Ran tests after the refactor to confirm they all pass.
=> Refactor to MirageJS

CHANGELOG.md, src/ModalManager.js, src/consts.js, test/bigtest/tests/check-in-test.js, translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-164
Ask the user to confirm check in when an item with the status Aged to lost is checked in.
=> UICHKIN-164: Add Aged to lost modal when item checked in

CHANGELOG.md, package.json, src/util.js
Values passed to `react-to-print` need to be escaped because of the way
it generates its document under the hood. Without escaping, if we passed
a value like `something<bad>very bad`, this would cause React to blow up
when slips were generated with an error like
```
ERROR:Failed to execute 'createElement' on 'Document':The tag name
provided ('bad') is not a valid name.
```
Refs [UICHKIN-193](https://issues.folio.org/browse/UICHKIN-193)
=> UICHKIN-193 html-encode strings for react-to-print

CHANGELOG.md, src/CheckIn.js
Fixed issue where tooltip was rendering below the button and on top of the dropdown on the actions menu.
https://issues.folio.org/browse/UICHKIN-198
=> UICHKIN-198: Update tooltip placement

CHANGELOG.md, src/CheckIn.js, src/ModalManager.js
Use the stripes-components versions of `<FormattedDate>` and
`<FormattedTime>` because they do not choke on the timestamps that are
provided by some backend modules.
Refs [UICHKIN-195](https://issues.folio.org/browse/UICHKIN-195), [STCOM-659](https://issues.folio.org/browse/STCOM-659)
=> UICHKIN-195 handle malformed timestamps

CHANGELOG.md, src/Scan.js
https://issues.folio.org/browse/UICHKIN-207
The `checkinNotesMode` was left set to `true` in some cases which caused issues when more than one item was check-in.
=> UICHKIN-207: Clear state after successful checkin or cancel

CHANGELOG.md, src/Scan.js, src/components/ConfirmStatusModal/ConfirmStatusModal.js, translations/ui-checkin/en.json, translations/ui-checkin/en_US.json
https://issues.folio.org/browse/UICHKIN-208
This adds a second line to the `<ConfirmStatusModal>` message with the request record's patron comment, if there is one.
=> UICHKIN-208: Display patron comments in <ConfirmStatusModal>

translations/ui-checkin/en_US.json
Weirdly, _only_ the en_US translation file failed to pick up the apostrophe removal for UICHKIN-211.
=> UICHKIN-211: Fix en_US translation

CHANGELOG.md, src/util.js, test/bigtest/tests/util-test.js
Fix `<Barcode>` tag processing caused by fix https://github.com/folio-org/ui-checkin/pull/341
https://issues.folio.org/browse/UICHKIN-220
=> UICHKIN-220 - Barcode image not rendering on staff slips - fails gracefully

CHANGELOG.md, src/Scan.js, test/bigtest/tests/check-in-test.js, translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-210
Added display of the `ErrorModal` when trying to check in an item with the `Intellectual item` status.
=> UICHKIN-210: Prevent check in for intellectual item status

CHANGELOG.md, src/ModalManager.js, src/consts.js, src/util.js, test/bigtest/tests/check-in-test.js, translations/ui-checkin/en.json
https://issues.folio.org/browse/UICHKIN-120
The user will have to confirm before `check in` an item with one of the statuses: `Long missing`, `In process (non-requestable)`, `Unavailable`, `Unknown`.
=> UICHKIN-120: Add confirmation modal for 4 new item statuses

CHANGELOG.md, src/CheckIn.js
Adds support for an optional `readyPrefix` property at the module level in stripes.config.js. If set, this prefix will be displayed in the title when the app is ready to receive a scanned item barcode.
=> UICHKIN-224 Optional prefix to indicate scan readiness in title

CHANGELOG.md, package.json
The only breaking change in `circulation` `10.0` was the removal of the
`override-check-out-by-barcode` which is not used here, hence continuing
to support `9.0`.
Refs [UICHKIN-244](https://issues.folio.org/browse/UICHKIN-244)
=> UICHKIN-244 also support circulation 10.0

CHANGELOG.md, src/components/PrintButton/PrintButton.css, src/components/PrintButton/PrintButton.js
All of the content is printed so that it's readable.
We don't need scroll for correct render our content before print.
https://issues.folio.org/browse/UICHKIN-245
Before
After
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UICHKIN-245: Fix content cut off for two-page staff slips

CHANGELOG.md, package.json
The only available permission set, `ui-checkin.all`, was missing
fee/fine-related permissions, causing errors on check-in for items with
associated fees/fines:
* `accounts.collection.get`
* `lost-item-fees-policies.collection.get`
Refs [UICHKIN-253](https://issues.folio.org/browse/UICHKIN-253)
=> UICHKIN-253 include fee/fine-related permissions

CHANGELOG.md, package.json
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UICHKIN-254
=> UICHKIN-254: Update circulation interface dependency to support v11

CHANGELOG.md, src/util.js
https://issues.folio.org/browse/UICHKIN-234
Check-in allows the user to backdate the date/time recorded as the check-in time, but the prior implementation didn't take daylight savings time into account. I didn't find an especially elegant way to do so, but I think this works. I'm one of those people who enjoys the DST transitions for the bit of spice they add to life, but having to work with them in code is no fun at all.
=> UICHKIN-234: Fix bug in backdating checkin time

CHANGELOG.md, karma.conf.js
Fix failed build on ui-checkin
Use karma.conf.js that consistency with other modules (https://github.com/folio-org/ui-users/blob/master/karma.conf.js)
https://issues.folio.org/browse/UICHKIN-265
jenkins
jenkins
local
=> UICHKIN-265: Fix failed build on ui-checkin

CHANGELOG.md, src/CheckIn.js, src/util.js
Fix incorrect check in time
`change('item.checkinTime', now.format().substring(11));` - set to `Timepicker` time with time zone.
After changes above `Timepicker`  always return time with time zone.
Remove obsolete code 
https://issues.folio.org/browse/UICHKIN-219
=> UICHKIN-219: Fix incorrect check in time.

CHANGELOG.md, src/components/ConfirmStatusModal/ConfirmStatusModal.js, src/components/RouteForDeliveryModal/RouteForDeliveryModal.js
Fix import paths
Component imports should happen through the @folio/stripes/${repo} namespace rather than directly via the repo's private path. e.g. prefer
`import LocationSelection from '@folio/stripes/smart-components/LocationSelection';`
instead of
`import LocationSelection from '@folio/stripes-smart-components/lib/LocationSelection';`
In current case we cannot fix path because we import css file and we should use path to file(example in section screenshot).
But we can use `ModalFooter`  component instead of importing css file.
We can remove `mfCss.modalFooterButton` because current class was removed from css https://github.com/folio-org/stripes-components/blob/master/lib/ModalFooter/ModalFooter.css
We can change  from `<div className={mfCss.modalFooterButtons}>` to `<ModalFooter>` …
=> UICHKIN-256: Fix import paths

src/components/ConfirmStatusModal/ConfirmStatusModal.js
Refs UICHKIN-273
When rendering a list in React, you have to provide a `key` attibute on
the list item. It's [the rule](https://reactjs.org/docs/lists-and-keys.html).
Provide the message-parts as `key`; we don't have anything else. 
[UICHKIN-273](https://issues.folio.org/browse/UICHKIN-273); see also #456, an inferior version of this PR which wrongly used the iteration index as a key.
=> UICHKIN-273 provide unique key in array iteration

CHANGELOG.md, test/bigtest/tests/check-in-test.js
Fix failed build on ui-checkin
Add skip for test (this test successfully pass locally but fails on jenkins). We should investigate this problem in separate task https://issues.folio.org/browse/UICHKIN-303
https://issues.folio.org/browse/UICHKIN-302
locally
jenkins
=> UICHKIN-302: Fix failed build on ui-checkin

CHANGELOG.md, package.json
Upgrade `@folio/react-intl-safe-html` for compatibility with
`@folio/stripes` `v7` (react 17, react-intl 5).
Refs [UICHKIN-308](https://issues.folio.org/browse/UICHKIN-308), [STRIPES-769](https://issues.folio.org/browse/STRIPES-769)
=> UICHKIN-308 upgrade react-intl-safe-html

CHANGELOG.md, src/components/FeeFineDetailsButton/FeeFineDetailsButton.js, src/components/FeeFineDetailsButton/FeeFineDetailsButton.test.js, test/bigtest/interactors/check-in.js, test/bigtest/network/scenarios/account.js, test/bigtest/network/scenarios/accounts.js, test/bigtest/tests/fee-fine-test.js, test/jest/__mock__/stripesComponents.mock.js
Fix the issue when fee/fine details doesn't open up if fee/fines have been refunded
Now we looking not only for fee/fines with status "Open", but for "Closed" too.
If we have several fee/fines with "Open" status - the button will redirect into view pane, with open fee/fines. If we have only one open fee/fine - the button will redirect directly on it.
This behaviout don't depend on number of "Closed" fee/fines.
The next case - when we have no open fee/fines, but have with status closed.
Redirect policy works here like with open fee/fines. If their number greate than one - the button will redirect you into view pane with closed fee/fines. And if we have only one - redirect directly on it.
And finaly if we have no fee/fines at all, the button will not be rendered.
This behavior was discussed …
=> UICHKIN-312: fix fee/fine details button

CHANGELOG.md, src/Scan.js, src/consts.js
We should use constants instead of hardcoded value for query limits.
Limits was upgraded to `1000`, it was tested on kiwi env - everything is fine.
I also removed default export of empty object from constants. I believe it was added to trick one of the linter rules, which prefere default export instead of named. But now we don't need it any more because we have more than one export from constants file.
https://issues.folio.org/browse/UICHKIN-317
=> UICHKIN-317: use constants instead of hardcoded value for query limits

CHANGELOG.md, src/Scan.js, test/bigtest/tests/check-in-test.js, translations/ui-checkin/en.json
Unhandled errors should bubble up on UI to say that somethin go wrong.
As you can see on screenshot below, I simulate error with 500 `statusCode` and content type `text`.
In code we have only one error which we directly handle, when `item` with passed `barcode` is not founded. All other errors will show modal with `this is an unhandled exception` text.
All tests will pass after https://github.com/folio-org/ui-checkin/pull/484 will be merged.
https://issues.folio.org/browse/UICHKIN-163
=> UICHKIN-163: unhandled errors bubble up on UI

CHANGELOG.md, package.json, test/bigtest/tests/automated-end-session-test.js
Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UICHKIN-319
=> UICHKIN-319: Also support circulation 13.0

CHANGELOG.md, src/Scan.js, src/components/SelectItemModal/SelectItemModal.css, src/components/SelectItemModal/SelectItemModal.js, src/components/SelectItemModal/index.js, test/bigtest/interactors/check-in.js, test/bigtest/interactors/select-item-modal.js, test/bigtest/network/factories/item.js, test/bigtest/network/factories/request.js, test/bigtest/tests/automated-end-session-test.js, test/bigtest/tests/check-in-test.js, test/bigtest/tests/check-in-with-claimed-returned-test.js, translations/ui-checkin/en.json
The purpose is to display a list of items with similar barcodes to the one entered by the staff member (based on a right-truncated wildcard query) so that a staff member can select the correct item to perform a check in transaction on.
To do this the staff member should enable the wildcard in Settings - Circulation - other settings - perform wildcard lookup. 
When the wildcard is enabled the barcode will be with '*' in the query.
After entering the barcode, a modal window will show up with a list of items with similar barcodes.
By clicking on the list item check-in modal will be available (screen 2)
https://issues.folio.org/browse/UICHKIN-309
=> UICHKIN-309: Perform Wildcard Item Lookup Before Performing Check in Transactions in Check in App

CHANGELOG.md, src/util.js, src/util.test.js
Dates in check-in module doesn't match expected format when printing staff slip (expected result from circulation staff slip templates).
https://issues.folio.org/browse/UICHKIN-320
before:
after:
=> UICHKIN-320: Fix date formats when slip print

CHANGELOG.md, package.json
Compile Translation Files into AST Format.
- Destination folder was renamed for consistency with other modules (Just for example https://github.com/folio-org/ui-users/blob/master/package.json#L843)
- We run locally command "yarn formatjs-compile" and we don't get any errors.
https://issues.folio.org/browse/UICHKIN-329
Hello @zburke 
Could you please confirm that Jenkinsfile are deprecated and we don't need add 
`runScripts = [
['formatjs-compile': ''],
]`
to Jenkinsfile.?
=> UICHKIN-243: Compile Translation Files into AST Format

CHANGELOG.md, src/Scan.js
Heading of `request delivery` slips should be consistent.
`convertToSlipData` accept `slipName` which is `Hold` by default. We just need to pass correct value for delivery modal.
Also I should note that these values are not localized.
Localization will be discussed with PO as a separate task/story.
https://issues.folio.org/browse/UICHKIN-334
before:
after:
=> UICHKIN-334: fix heading of `Request delivery slip`

CHANGELOG.md, src/components/ClaimedReturnedModal/ClaimedReturnedModal.js, src/components/ClaimedReturnedModal/ClaimedReturnedModal.test.js, test/jest/__mock__/stripesComponents.mock.js, test/jest/helpers/index.js, test/jest/helpers/utils.js
Add Jest/RTL testing for `ClaimedReturnedModal` component in `src\components\ClaimedReturnedModal`.
https://issues.folio.org/browse/UICHKIN-280
=> UICHKIN-280: Add Jest/RTL tests for `ClaimedReturnedModal` component

CHANGELOG.md, src/ModalManager.js, src/ModalManager.test.js, test/jest/__mock__/stripesComponents.mock.js
Add Jest/RTL testing for `ModalManager` component.
https://issues.folio.org/browse/UICHKIN-288
=> UICHKIN-288: Add Jest/RTL tests for `ModalManager` component

CHANGELOG.md, src/Scan.js
Initially when we go to Checkin service, change service point and then try to check in some item we sent incorrect `servicePointId` param to the server.
[UICHKIN-344](https://issues.folio.org/browse/UICHKIN-344)
=> UICHKIN-344: Switching service points is not recognized by the check-in app

CHANGELOG.md, package.json
Add version 12.0 to the list of supported inventory interface versions.
DELETE /inventory/instances and DELETE /inventory/items have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-checkin doesn't need any code change because it doesn't use these two DELETE APIs.
=> UICHKIN-357: Support inventory 12.0 in okapiInterfaces

CHANGELOG.md, package.json
Bump major versions of several @folio/stripes-* packages.
[UICHKIN-369](https://issues.folio.org/browse/UICHKIN-369)
=> UICHKIN-369: bump stripes to 8.0.0 for Orchid/2023-R1

CHANGELOG.md, src/components/CheckinNoteModal/CheckInNoteModal.test.js, src/components/ClaimedReturnedModal/ClaimedReturnedModal.test.js, src/components/ConfirmStatusModal/ConfirmStatusModal.test.js, test/jest/__mock__/stripesComponents.mock.js
- Use camel case notation for all data-testid
- Remove magic strings for testIds and labelIds
https://issues.folio.org/browse/UICHKIN-375
=> UICHKIN-375: Use camel case notation for all data-testid

CHANGELOG.md, package.json, test/jest/babel.config.js
Upgrade babel config
Pulling the babel config directly from stripes-webpack via stripes-cli, in order to guarantee the babel plugins, versions, and config are all aligned.
https://issues.folio.org/browse/UICHKIN-389
=> UICHKIN-389: Upgrade babel config

CHANGELOG.md, package.json, src/CheckIn.js
When a user goes to **checkin** page and check in an item and then log out, we can see unnecessary "end-patron-action-session" request.
This request will fail because there is no required token.
Furthermore, that request should not be sent if a user is logged out.
Also, I found not removed event listeners that could lead to memory leaks.
See the same implementation for checkout module [here](https://github.com/folio-org/ui-checkout/pull/826)
The best solution that I found is using global object "window" to store timer entity. In this case timer will be available through all app, even on the login page that is necessary for us.
Also, I tried an approach with local resources (manifest) but on the login page data was lost.
[UICHKIN-392](https://issues.folio.org/browse/UICHKIN-392) …
=> UICHKIN-392: Circulation time out error - permission problem

CHANGELOG.md, package.json
Also support `feesfines` interface version `19.0`
Changes was in endpoint `/accounts` the field `status` has become required, this does not affect the current module.
This is part of `Quesnelia (R1 2024)` release
Should be merged after merging https://issues.folio.org/browse/MODFEE-337
https://issues.folio.org/browse/UICHKIN-401
=> UICHKIN-401: Also support feesfines interface version 19.0

CHANGELOG.md, src/CheckIn.js, src/components/FeeFineDetailsButton/FeeFineDetailsButton.js, src/components/FeeFineDetailsButton/FeeFineDetailsButton.test.js, src/consts.js, src/util.js, src/util.test.js
Link to master branch PR - https://github.com/folio-org/ui-checkin/pull/606
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's …
=> UICHKIN-398-poppy-dcb - Hide fee/fine action menu items when requester is virtual user.

CHANGELOG.md, src/CheckIn.js, src/components/FeeFineDetailsButton/FeeFineDetailsButton.test.js, src/consts.js, src/util.js, src/util.test.js
[UICHKIN-403](https://issues.folio.org/browse/UICHKIN-403) - [DCB] Check-in: Hide “Item details” option in Actions menu (Borrowing library)
When the scanned item has its instance id and holdingsRecordId equal to DCB_INSTANCE_ID and DCB_HOLDINGS_RECORD_ID, the item is treated as virtual item and hence, "item details" action menu item is hidden.
Borrowing role -
Pickup role - checkin1
Pickup role - checkin2
- Are the JIRAs under …
=> UICHKIN-403 - Hide “Item details” option in Actions menu when item is virtual

CHANGELOG.md, src/Scan.js, src/Scan.test.js, src/consts.js
Cover Scan by jest/RTL tests
[UICHKIN-289](https://issues.folio.org/browse/UICHKIN-289)
Coverage of Scan component will be increased in the scope of another ticket (UICHKIN-412)
=> UICHKIN-289: UI tests replacement with RTL/Jest for view Scan (part 1)

CHANGELOG.md, src/util.js, src/util.test.js
If the time zone is currently in DST, and the return needs to be backdated to a time in non-DST, the logic applies a 1hour offset prior to submitting the time. When the time is presented in the checked-in items list, the time displayed has a 1 hour difference from the time that was entered by the user.
Remove DST compensation code that was added back in [UICHKIN-234](https://folio-org.atlassian.net/browse/UICHKIN-234) Timepicker applies no offset to its output time string. It's supplied with `UTC` here, regardless of the tenant-set timeZone. Appropriate time localization happens courtesy of the date to determine a datetime string is DST or not given its time zone/locale information. `FormattedDate` is smart enough to know this, so it needs no pre-adjustment of the time value when it …
=> UICHKIN-420 - Time offset issue when crossing DST boundary. 

src/components/ComponentToPrint/ComponentToPrint.js
Only certain HTML tags should be rendered when displaying staff slips. Add support for `Barcode `tag with sanitize.
https://issues.folio.org/browse/UICHKIN-421
For resolve current problem we should use `DOMPurify.sanitize` confirmed with John. Add support for Barcode tag with sanitize. Change log was already updated.
=> UICHKIN-421: Add support for Barcode tag with sanitize

CHANGELOG.md, src/Scan.js
Remove barcode trimming before it is sent to backend for processing.
[UICHKIN-424](https://folio-org.atlassian.net/browse/UICHKIN-424)
=> UICHKIN-424: Check in - Do not trim barcode before it is sent to backend for processing

CHANGELOG.md, package.json, src/Scan.js
Implement feature toggle for switch between `circulation/check-in-by-barcode` and `circulation-bff/loans/check-in-by-barcode`
`circulation/check-in-by-barcode` should be used when `stripes config enableEcsRequests` **absent**
`circulation-bff/loans/check-in-by-barcode` should be used when` stripes config enableEcsRequests` **present**
https://issues.folio.org/browse/UICHKIN-439
=> UICHKIN-439: Implement feature toggle for switch between circulation/check-in-by-barcode and circulation-bff/loans/check-in-by-barcode

CHANGELOG.md, src/Checkin.test.js
Some jest related packages have dependency on nwsapi package.
Due to that dependency we can not correctly mock callback passed to addEventListener.
[UICHKIN-468](https://folio-org.atlassian.net/browse/UICHKIN-468)
=> UICHKIN-468: Remove failed tests after packages updating

src/util.js
Fix time conversion issue
- We get time with time offset. After convert offset applied to time and we get wrong time. We should use time as is (That was selected by user). 
- This is follow up pull request that associated with https://github.com/folio-org/ui-checkin/pull/678 And change log was updated in scope of previous pull request.
https://issues.folio.org/browse/UICHKIN-467
=> UICHKIN-467: Fix time conversion issue
